In [3]:
import networkx as nx
import numpy as np

# read
file_path = 'pr.edgelist'
G = nx.read_edgelist(file_path, create_using=nx.DiGraph(), nodetype=int)
# node
n = nx.number_of_nodes(G)
# clear
A = nx.to_numpy_array(G, nodelist=range(n), weight=None)
print(A)

[[0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
def update(A, v, d, k):
    # get
    n = len(G.nodes)  
    # change
    A = nx.to_numpy_array(G)  

    for _ in range(k): 
        
        v = d * np.dot(A, v) + (1-d)*(1/n)  
    return (v)  

n = len(G.nodes)
d = 0.85
k = 20
v = np.ones(n) / n
v = update(G, v, d, k)
    
for i, vs in enumerate(v):
    print(f"Node {i}: Import level {vs}")
v = nx.pagerank(G)
    
for i, vs in enumerate(v):
    print(f"Node {i}: Import level {vs}")

Node 0: Import level 0.17338426132812496
Node 1: Import level 0.0716521640625
Node 2: Import level 0.06716562499999999
Node 3: Import level 0.05045781249999999
Node 4: Import level 0.0989849765625
Node 5: Import level 0.06959078125
Node 6: Import level 0.03215625
Node 7: Import level 0.061082812499999986
Node 8: Import level 0.03215625
Node 9: Import level 0.0125
Node 10: Import level 0.0125
Node 11: Import level 0.023125


ModuleNotFoundError: No module named 'scipy'